name: CI to Docker Hub (max4com/phpmyadmin)

on:
  workflow_dispatch:

jobs:
  
  build:
    name: "[ phpMyAdmin-${{ matrix.version }} ]"
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'apache'
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.run_number }}-${{ matrix.version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.run_number }}-${{ matrix.version }}-
      - 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and push phpMyAdmin-${{ matrix.version }}
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.version }}
          file: ./${{ matrix.version }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/phpmyadmin:${{ matrix.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - 
        name: Image digest phpMyAdmin-${{ matrix.version }}
        run: echo ${{ steps.docker_build.outputs.digest }}
